name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install -g @platane/snk
          npx --yes @platane/snk --user 0xC1ph3rX --output snake.svg --color "#00FF41"
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update snake.svg"
          branch: main
